language: node_js
node_js:
  - '8.9.1'
before_install:
  - openssl aes-256-cbc -K $encrypted_56062cdd2e1c_key -iv $encrypted_56062cdd2e1c_iv
    -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host 39.108.2.49\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script: true
after_success:
  - ssh root@39.108.2.49 'cd /site-cquwinner/react/CQUTeam/react && git pull && npm run build:pro'
